services:
  mlops-iris-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile 
    expose:
      - "8000"

  nginx:
    build:
      context: deployments/nginx/
      dockerfile: Dockerfile
    container_name: nginx_revproxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployments/nginx/certs:/etc/nginx/certs:ro
      - ./deployments/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - mlops-iris-api