[project]
name = "nginx-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.12",
    "joblib==1.5.1",
    "numpy==2.2.6",
    "scikit-learn==1.6.1",
    "uvicorn==0.34.3",
]
