version: 1
formatters:
  default:
    format: "%(asctime)s | %(levelname)s | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
loggers:
  uvicorn:
    handlers: [console]
    level: INFO
  uvicorn.error:
    handlers: [console]
    level: INFO
  uvicorn.access:
    handlers: [console]
    level: INFO